export RIANA_API_URL='https://manage.riana.refinitiv.com/v1'
export RIANA_API_AUTHORIZATION_TOKEN='Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJYNTAwOTQ1IiwiYXV0aCI6Ilg1MDA5NDUtc2FuZGJveCwgZGVmYXVsdCIsImp0aSI6Ilg1MDA5NDUxNjg3NjM4NzcyMzEzIiwiZXhwIjoxNjg3NjM4NzcyfQ.yMihN6pqrItql5vdp1gpIlrkhD0HHgsQRKScPXe4mRkLFqIa8y_bmc-Kz5eusXtn3cTkO3hCR_EyOWRd9COK-Q'
